# Generated by Django 3.0.6 on 2020-08-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial_name', models.CharField(max_length=255, null=True)),
                ('service_point_email', models.CharField(max_length=255, null=True)),
                ('cn', models.CharField(max_length=255, null=True)),
                ('rg_hpsm', models.CharField(max_length=255, null=True)),
                ('rg_kuc_hpsm', models.CharField(max_length=255, null=True)),
                ('ss_adress', models.TextField(null=True)),
                ('rg_hpsm_coordinator', models.TextField(null=True)),
                ('post_system_contact', models.TextField(null=True)),
                ('work_problems', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('service_uz_name', models.CharField(max_length=255, null=True)),
                ('dss_cert_thumbrint', models.CharField(max_length=255, null=True)),
                ('dss_cert_valid_to', models.DateTimeField(null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Filials')),
            ],
        ),
    ]
