# Generated by Django 3.1 on 2020-09-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ais_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkziType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skzis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skziuser_name', models.CharField(blank=True, max_length=512, null=True)),
                ('skziserial_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pvmserial_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pechat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.CharField(blank=True, max_length=1024, null=True)),
                ('szz', models.CharField(blank=True, max_length=255, null=True)),
                ('catalognumber', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('sertificate', models.CharField(blank=True, max_length=255, null=True)),
                ('ais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skzis.ais')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.organizations')),
                ('skzi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skzis.skzitype')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skzis.software')),
            ],
        ),
    ]
