# Generated by Django 3.1 on 2020-08-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('e_mail', models.CharField(max_length=255, null=True)),
                ('work_telephone', models.CharField(max_length=255, null=True)),
                ('mobile_telephone', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('filial_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DLNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('inn', models.CharField(max_length=255)),
                ('full_organization_name', models.CharField(max_length=512)),
                ('organization_name', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=1024)),
                ('doc_num', models.CharField(max_length=1024)),
                ('doc_date', models.DateTimeField(blank=True, null=True)),
                ('order_start_date', models.DateTimeField(blank=True, null=True)),
                ('order_end_date', models.DateTimeField(blank=True, null=True)),
                ('document_price', models.CharField(blank=True, max_length=255, null=True)),
                ('document_price_with_nds', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_prepare_date', models.DateTimeField(blank=True, null=True)),
                ('doc_eosdo_date', models.DateTimeField(blank=True, null=True)),
                ('doc_sending_date', models.DateTimeField(blank=True, null=True)),
                ('order_activity_date', models.DateTimeField(blank=True, null=True)),
                ('doc_eosdo_num', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_eosdo_link', models.CharField(blank=True, max_length=512, null=True)),
                ('order_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.orderactivities')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.orderstatuses')),
            ],
        ),
        migrations.CreateModel(
            name='Order_admin_ib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=255, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_file', models.FileField(blank=True, null=True, upload_to='mainapp/static/mainapp/admin_ib_orders')),
                ('order_administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.administrators')),
                ('order_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.organizations')),
            ],
        ),
        migrations.AddField(
            model_name='administrators',
            name='dl_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrators.dlnames'),
        ),
    ]
